#!/usr/bin/env python3
"""Reconstruct and compare ASK simulation waveforms.

Inputs generated by the SystemVerilog testbench:
    sim/out/baseband_symbols.csv
    sim/out/sim_samples.csv
    sim/out/tb_config.csv

Other input:
    sim/tb/carrier_sine.mem

Outputs:
    sim/out/python_golden_samples.csv
    sim/out/waveform_compare.png
"""

from __future__ import annotations

import argparse
import csv
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence


SCRIPT_DIR = Path(__file__).resolve().parent
SIM_DIR = SCRIPT_DIR.parent
REPO_ROOT = SIM_DIR.parent
OUT_DIR = SIM_DIR / "out"

os.environ.setdefault("MPLCONFIGDIR", str(OUT_DIR / ".mplconfig"))


@dataclass(frozen=True)
class BasebandInterval:
    symbol_index: int
    start_cycle: int
    end_cycle: int
    symbol_dec: int
    scale: int


@dataclass
class GoldenState:
    phase_acc: int = 0
    carrier: int = 0
    scale: int = 0
    full_mult: int = 0
    ask: int = 0


def read_config(path: Path) -> Dict[str, str]:
    if not path.exists():
        return {}

    with path.open(newline="") as config_file:
        rows = csv.DictReader(config_file)
        return {row["key"]: row["value"] for row in rows}


def config_int(config: Dict[str, str], key: str, default: int) -> int:
    value = config.get(key)
    if value is None or value == "":
        return default
    return int(value, 0)


def read_rows(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="") as csv_file:
        return list(csv.DictReader(csv_file))


def parse_int_field(row: Dict[str, str], name: str) -> int:
    return int(row[name], 0)


def signed_from_raw(raw_value: int, width: int) -> int:
    sign_bit = 1 << (width - 1)
    mask = (1 << width) - 1
    raw_value &= mask
    if raw_value & sign_bit:
        return raw_value - (1 << width)
    return raw_value


def fit_signed(value: int, width: int) -> int:
    return signed_from_raw(value, width)


def read_sine_mem(path: Path, width: int) -> List[int]:
    samples: List[int] = []
    with path.open() as mem_file:
        for line_number, line in enumerate(mem_file, start=1):
            text = line.strip()
            if not text or text.startswith("//"):
                continue
            try:
                raw_value = int(text, 16)
            except ValueError as exc:
                raise ValueError(f"invalid hex value in {path}:{line_number}: {text}") from exc
            samples.append(signed_from_raw(raw_value, width))
    return samples


def read_baseband(path: Path) -> List[BasebandInterval]:
    intervals: List[BasebandInterval] = []
    for row in read_rows(path):
        intervals.append(
            BasebandInterval(
                symbol_index=parse_int_field(row, "symbol_index"),
                start_cycle=parse_int_field(row, "start_cycle"),
                end_cycle=parse_int_field(row, "end_cycle"),
                symbol_dec=parse_int_field(row, "symbol_dec"),
                scale=parse_int_field(row, "scale"),
            )
        )
    intervals.sort(key=lambda item: item.start_cycle)
    return intervals


def symbol_to_scale(symbol: int, mult_w: int) -> int:
    scale_max = (1 << mult_w) - 1
    if symbol == 0b00:
        return 0
    if symbol == 0b01:
        return scale_max // 3
    if symbol == 0b11:
        return (scale_max * 2) // 3
    if symbol == 0b10:
        return scale_max
    return 0


def symbol_at_cycle(cycle: int, intervals: Sequence[BasebandInterval], fallback: int) -> int:
    for interval in intervals:
        if cycle < interval.start_cycle:
            break
        if interval.start_cycle <= cycle <= interval.end_cycle:
            return interval.symbol_dec
    return fallback


def build_symbol_timeline(
    *,
    max_cycle: int,
    intervals: Sequence[BasebandInterval],
    sample_symbols: Dict[int, int],
) -> Dict[int, int]:
    timeline: Dict[int, int] = {}
    interval_index = 0
    current_symbol = 0

    for cycle in range(1, max_cycle + 1):
        while interval_index < len(intervals) and cycle > intervals[interval_index].end_cycle:
            interval_index += 1

        if interval_index < len(intervals):
            interval = intervals[interval_index]
            if interval.start_cycle <= cycle <= interval.end_cycle:
                current_symbol = interval.symbol_dec
            elif cycle < interval.start_cycle:
                current_symbol = sample_symbols.get(cycle, current_symbol)
        else:
            current_symbol = sample_symbols.get(cycle, current_symbol)

        timeline[cycle] = current_symbol

    return timeline


def multiply_model(carrier: int, scale: int) -> int:
    return carrier * scale


def reconstruct_golden(
    *,
    sim_rows: Sequence[Dict[str, str]],
    intervals: Sequence[BasebandInterval],
    sine_samples: Sequence[int],
    phase_w: int,
    lut_addr_w: int,
    amp_w: int,
    mult_w: int,
    phase_inc: int,
) -> List[Dict[str, int]]:
    if not sim_rows:
        return []

    cycles = [parse_int_field(row, "cycle") for row in sim_rows]
    max_cycle = max(cycles)
    phase_mask = (1 << phase_w) - 1
    addr_mask = (1 << lut_addr_w) - 1
    sample_symbols = {
        parse_int_field(row, "cycle"): parse_int_field(row, "symbol_dec") for row in sim_rows
    }
    symbols = build_symbol_timeline(
        max_cycle=max_cycle,
        intervals=intervals,
        sample_symbols=sample_symbols,
    )

    state = GoldenState()
    golden_by_cycle: Dict[int, Dict[str, int]] = {}

    for cycle in range(1, max_cycle + 1):
        symbol = symbols.get(cycle, 0)
        scale = symbol_to_scale(symbol, mult_w)
        phase_addr = (state.phase_acc >> (phase_w - lut_addr_w)) & addr_mask
        next_phase_acc = (state.phase_acc + phase_inc) & phase_mask
        next_carrier = sine_samples[phase_addr]
        next_scale = scale
        next_full_mult = multiply_model(state.carrier, state.scale)
        next_ask = fit_signed(state.full_mult >> mult_w, amp_w)

        state.phase_acc = next_phase_acc
        state.carrier = next_carrier
        state.scale = next_scale
        state.full_mult = next_full_mult
        state.ask = next_ask

        golden_by_cycle[cycle] = {
            "cycle": cycle,
            "symbol_dec": symbol,
            "scale": state.scale,
            "phase_addr": phase_addr,
            "golden_carrier": state.carrier,
            "golden_ask": state.ask,
        }

    merged: List[Dict[str, int]] = []
    for row in sim_rows:
        cycle = parse_int_field(row, "cycle")
        golden = golden_by_cycle[cycle]
        carrier_dut = parse_int_field(row, "carrier_dut")
        ask_dut = parse_int_field(row, "ask_dut")
        merged.append(
            {
                "cycle": cycle,
                "time_ns": parse_int_field(row, "time_ns"),
                "symbol_dec": golden["symbol_dec"],
                "scale": golden["scale"],
                "phase_addr": golden["phase_addr"],
                "carrier_dut": carrier_dut,
                "ask_dut": ask_dut,
                "golden_carrier": golden["golden_carrier"],
                "golden_ask": golden["golden_ask"],
                "carrier_error": carrier_dut - golden["golden_carrier"],
                "ask_error": ask_dut - golden["golden_ask"],
            }
        )

    return merged


def write_golden_csv(path: Path, rows: Sequence[Dict[str, int]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "cycle",
        "time_ns",
        "symbol_dec",
        "scale",
        "phase_addr",
        "carrier_dut",
        "ask_dut",
        "golden_carrier",
        "golden_ask",
        "carrier_error",
        "ask_error",
    ]
    with path.open("w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def select_plot_rows(
    rows: Sequence[Dict[str, int]],
    *,
    start_cycle: int,
    max_samples: int,
) -> List[Dict[str, int]]:
    selected = [row for row in rows if row["cycle"] >= start_cycle]
    if max_samples > 0:
        selected = selected[:max_samples]
    return selected


def as_list(rows: Sequence[Dict[str, int]], field: str) -> List[int]:
    return [row[field] for row in rows]


def plot_comparison(
    *,
    rows: Sequence[Dict[str, int]],
    image_path: Path,
    title: str,
) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise SystemExit("matplotlib is required to generate the PNG comparison") from exc

    image_path.parent.mkdir(parents=True, exist_ok=True)

    time_us = [row["time_ns"] / 1000.0 for row in rows]
    scale = as_list(rows, "scale")
    carrier_dut = as_list(rows, "carrier_dut")
    ask_dut = as_list(rows, "ask_dut")
    golden_carrier = as_list(rows, "golden_carrier")
    golden_ask = as_list(rows, "golden_ask")
    carrier_error = as_list(rows, "carrier_error")
    ask_error = as_list(rows, "ask_error")

    fig, axes = plt.subplots(4, 1, figsize=(14, 10), sharex=True, constrained_layout=True)
    fig.suptitle(title)

    axes[0].step(time_us, scale, where="post", color="tab:green", linewidth=1.1)
    axes[0].set_ylabel("scale")
    axes[0].set_title("Random baseband amplitude scale")
    axes[0].grid(True, alpha=0.3)

    axes[1].step(time_us, carrier_dut, where="post", label="DUT carrier", color="tab:blue", linewidth=1.0)
    axes[1].step(time_us, golden_carrier, where="post", label="Python golden carrier", color="tab:orange", linestyle="--", linewidth=0.9)
    axes[1].set_ylabel("carrier")
    axes[1].set_title("Carrier DDS")
    axes[1].legend(loc="upper right")
    axes[1].grid(True, alpha=0.3)

    axes[2].step(time_us, ask_dut, where="post", label="DUT ASK", color="tab:purple", linewidth=1.0)
    axes[2].step(time_us, golden_ask, where="post", label="Python golden ASK", color="tab:red", linestyle="--", linewidth=0.9)
    axes[2].set_ylabel("ASK")
    axes[2].set_title("ASK output")
    axes[2].legend(loc="upper right")
    axes[2].grid(True, alpha=0.3)

    axes[3].step(time_us, carrier_error, where="post", label="carrier error", color="tab:blue", linewidth=0.9)
    axes[3].step(time_us, ask_error, where="post", label="ASK error", color="tab:red", linewidth=0.9)
    axes[3].set_ylabel("error")
    axes[3].set_xlabel("time (us)")
    axes[3].set_title("DUT minus Python golden")
    axes[3].legend(loc="upper right")
    axes[3].grid(True, alpha=0.3)

    fig.savefig(image_path, dpi=150)
    plt.close(fig)


def max_abs(values: Iterable[int]) -> int:
    return max((abs(value) for value in values), default=0)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Reconstruct ASK golden waveforms and generate a DUT-vs-golden plot.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--config", type=Path, default=OUT_DIR / "tb_config.csv")
    parser.add_argument("--baseband", type=Path, default=OUT_DIR / "baseband_symbols.csv")
    parser.add_argument("--samples", type=Path, default=OUT_DIR / "sim_samples.csv")
    parser.add_argument("--carrier-mem", type=Path, default=SIM_DIR / "tb" / "carrier_sine.mem")
    parser.add_argument("--golden-csv", type=Path, default=OUT_DIR / "python_golden_samples.csv")
    parser.add_argument("--image", type=Path, default=OUT_DIR / "waveform_compare.png")
    parser.add_argument("--start-cycle", type=int, default=1)
    parser.add_argument("--max-samples", type=int, default=5000, help="0 means plot all samples")
    parser.add_argument("--phase-w", type=int, default=None)
    parser.add_argument("--lut-addr-w", type=int, default=None)
    parser.add_argument("--amp-w", type=int, default=None)
    parser.add_argument("--mult-w", type=int, default=None)
    parser.add_argument("--phase-inc", type=int, default=None)
    return parser


def resolve(path: Path) -> Path:
    return path.expanduser().resolve()


def main() -> int:
    args = build_arg_parser().parse_args()

    config_path = resolve(args.config)
    baseband_path = resolve(args.baseband)
    samples_path = resolve(args.samples)
    carrier_mem_path = resolve(args.carrier_mem)
    golden_csv_path = resolve(args.golden_csv)
    image_path = resolve(args.image)

    config = read_config(config_path)
    phase_w = args.phase_w if args.phase_w is not None else config_int(config, "phase_w", 32)
    lut_addr_w = args.lut_addr_w if args.lut_addr_w is not None else config_int(config, "lut_addr_w", 10)
    amp_w = args.amp_w if args.amp_w is not None else config_int(config, "amp_w", 16)
    mult_w = args.mult_w if args.mult_w is not None else config_int(config, "mult_w", 8)
    phase_inc = args.phase_inc if args.phase_inc is not None else config_int(config, "phase_inc", 42949673)

    sim_rows = read_rows(samples_path)
    intervals = read_baseband(baseband_path)
    sine_samples = read_sine_mem(carrier_mem_path, amp_w)

    expected_depth = 1 << lut_addr_w
    if len(sine_samples) != expected_depth:
        raise SystemExit(
            f"carrier LUT depth mismatch: expected {expected_depth}, got {len(sine_samples)}"
        )

    golden_rows = reconstruct_golden(
        sim_rows=sim_rows,
        intervals=intervals,
        sine_samples=sine_samples,
        phase_w=phase_w,
        lut_addr_w=lut_addr_w,
        amp_w=amp_w,
        mult_w=mult_w,
        phase_inc=phase_inc,
    )
    write_golden_csv(golden_csv_path, golden_rows)

    plot_rows = select_plot_rows(
        golden_rows,
        start_cycle=args.start_cycle,
        max_samples=args.max_samples,
    )
    if not plot_rows:
        raise SystemExit("no rows selected for plotting")

    carrier_error_max = max_abs(row["carrier_error"] for row in golden_rows)
    ask_error_max = max_abs(row["ask_error"] for row in golden_rows)
    title = (
        f"ASK waveform comparison "
        f"(phase_inc={phase_inc}, cycles {plot_rows[0]['cycle']}..{plot_rows[-1]['cycle']})"
    )
    plot_comparison(rows=plot_rows, image_path=image_path, title=title)

    print(f"Read {len(sim_rows)} simulation samples")
    print(f"Read {len(intervals)} baseband symbols")
    print(f"Wrote golden CSV: {golden_csv_path}")
    print(f"Wrote comparison image: {image_path}")
    print(f"Max carrier error: {carrier_error_max}")
    print(f"Max ASK error: {ask_error_max}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
